In [1]:
import numpy as np
np.set_printoptions(precision=5)

In [2]:
import stanpy as stp

s = {"EI":32000, "GA":20000, "N":-1000}
gamma, K = stp.gamma_K(**s)
print(gamma, K)

1.0526315789473684 -0.03289473684210526


In [3]:
import stanpy as stp

aj = stp.aj(x=[-1,0,2,3],n=5)
print(aj)

[[0.      0.      0.      0.      0.      0.     ]
 [1.      0.      0.      0.      0.      0.     ]
 [1.      2.      2.      1.33333 0.66667 0.26667]
 [1.      3.      4.5     4.5     3.375   2.025  ]]


In [4]:
import stanpy as stp

s = {"EI":32000, "GA":20000, "N":-1000}
bj = stp.bj(x=[-1,0,2,3],**s)
print(bj)

[[0.      0.      0.      0.      0.      0.     ]
 [1.      0.      0.      0.      0.      0.     ]
 [0.93493 1.95643 1.97817 1.32459 0.66375 0.26583]
 [0.85559 2.85415 4.39007 4.43386 3.34187 2.01078]]


In [5]:
import sympy as sym
import stanpy as stp

x = sym.Symbol("x")
E = 32000  # kN/m2
b = 0.2  # m
ha = hb = 0.3  # m
hc = 0.4  # m
l = 4  # m
hx = ha + (hc - hb) / l * x

cs_props = stp.cs(b=b, h=hx)
s = {"E": E, "cs": cs_props, "l": l}
bj = stp.bj(x=[-1,0,2,3,4],**s)
print(bj)

[[[ 0.       0.       0.54545 -0.1898   0.04869]
  [ 0.       0.      -1.1405   0.59504 -0.20262]]

 [[ 1.       0.       0.       0.       0.     ]
  [ 0.       1.       0.       0.       0.     ]]

 [[ 1.       2.       1.71429  1.0562   0.50369]
  [ 0.       1.       1.59184  1.46939  0.94129]]

 [[ 1.       3.       3.6      3.20794  2.24511]
  [ 0.       1.       2.16     2.88     2.71603]]

 [[ 1.       4.       6.       6.88538  6.29242]
  [ 0.       1.       2.625    4.5      5.55731]]]


In [6]:
import sympy as sym
import stanpy as stp

x = sym.Symbol("x")
E = 32000  # kN/m2
b = 0.2  # m
ha = hb = 0.3  # m
hc = 0.4  # m
l = 4  # m
q = 5 # kN/m
hx = ha + (hc - hb) / l * x

cs_props = stp.cs(b=b, h=hx)
s = {"E": E, "cs": cs_props, "l": l, "q":q}
li = stp.load_integral(x=[-1,0,2,3,4],**s)
print(li)

[[ 1.69052e-02 -7.03552e-02  0.00000e+00 -0.00000e+00  1.00000e+00]
 [ 0.00000e+00  0.00000e+00  0.00000e+00 -0.00000e+00  1.00000e+00]
 [ 1.74893e-01  3.26837e-01 -1.00000e+01 -1.00000e+01  1.00000e+00]
 [ 7.79550e-01  9.43065e-01 -2.25000e+01 -1.50000e+01  1.00000e+00]
 [ 2.18487e+00  1.92962e+00 -4.00000e+01 -2.00000e+01  1.00000e+00]]


In [7]:
import stanpy as stp

l = 5 #m
s = {"EI":32000, "GA":20000, "l":l, "q":2}
Fik = stp.tr(s, x=[0,l/2,l])
print(Fik)

[[[ 1.00000e+00  0.00000e+00  0.00000e+00  0.00000e+00  0.00000e+00]
  [ 0.00000e+00  1.00000e+00  0.00000e+00  0.00000e+00  0.00000e+00]
  [ 0.00000e+00  0.00000e+00  1.00000e+00  0.00000e+00  0.00000e+00]
  [ 0.00000e+00  0.00000e+00  0.00000e+00  1.00000e+00  0.00000e+00]
  [ 0.00000e+00  0.00000e+00  0.00000e+00  0.00000e+00  1.00000e+00]]

 [[ 1.00000e+00  2.50000e+00 -9.76563e-05  4.36198e-05 -2.10775e-04]
  [ 0.00000e+00  1.00000e+00 -7.81250e-05 -9.76563e-05  1.62760e-04]
  [ 0.00000e+00  0.00000e+00  1.00000e+00  2.50000e+00 -6.25000e+00]
  [ 0.00000e+00  0.00000e+00  0.00000e+00  1.00000e+00 -5.00000e+00]
  [ 0.00000e+00  0.00000e+00  0.00000e+00  0.00000e+00  1.00000e+00]]

 [[ 1.00000e+00  5.00000e+00 -3.90625e-04 -4.01042e-04  3.77604e-04]
  [ 0.00000e+00  1.00000e+00 -1.56250e-04 -3.90625e-04  1.30208e-03]
  [ 0.00000e+00  0.00000e+00  1.00000e+00  5.00000e+00 -2.50000e+01]
  [ 0.00000e+00  0.00000e+00  0.00000e+00  1.00000e+00 -1.00000e+01]
  [ 0.00000e+00  0.00000e+00  

In [8]:
import stanpy as stp

l = 5 #m
s1 = {"EI":32000, "GA":20000, "l":l, "q":2}
s2 = {"EI":32000, "GA":20000, "l":l, "q":2}
s = [s1,s2]

Fik = stp.tr(*s, x=np.linspace(0, 2*l, 3))
print(Fik)

[[[ 1.00000e+00  0.00000e+00  0.00000e+00  0.00000e+00  0.00000e+00]
  [ 0.00000e+00  1.00000e+00  0.00000e+00  0.00000e+00  0.00000e+00]
  [ 0.00000e+00  0.00000e+00  1.00000e+00  0.00000e+00  0.00000e+00]
  [ 0.00000e+00  0.00000e+00  0.00000e+00  1.00000e+00  0.00000e+00]
  [ 0.00000e+00  0.00000e+00  0.00000e+00  0.00000e+00  1.00000e+00]]

 [[ 1.00000e+00  5.00000e+00 -3.90625e-04 -4.01042e-04  3.77604e-04]
  [ 0.00000e+00  1.00000e+00 -1.56250e-04 -3.90625e-04  1.30208e-03]
  [ 0.00000e+00  0.00000e+00  1.00000e+00  5.00000e+00 -2.50000e+01]
  [ 0.00000e+00  0.00000e+00  0.00000e+00  1.00000e+00 -1.00000e+01]
  [ 0.00000e+00  0.00000e+00  0.00000e+00  0.00000e+00  1.00000e+00]]

 [[ 1.00000e+00  1.00000e+01 -1.56250e-03 -4.70833e-03  2.10417e-02]
  [ 0.00000e+00  1.00000e+00 -3.12500e-04 -1.56250e-03  1.04167e-02]
  [ 0.00000e+00  0.00000e+00  1.00000e+00  1.00000e+01 -1.00000e+02]
  [ 0.00000e+00  0.00000e+00  0.00000e+00  1.00000e+00 -2.00000e+01]
  [ 0.00000e+00  0.00000e+00  

In [9]:
import stanpy as stp

l = 5 #m
s = {"EI":32000, "GA":20000, "l":l, "q":2}
load_integral_Q = stp.calc_load_integral_Q(x=[0,l/2,l],**s)
print(load_integral_Q)

[[ 0.00000e+00  0.00000e+00  0.00000e+00  0.00000e+00  1.00000e+00]
 [-2.10775e-04  1.62760e-04 -6.25000e+00 -5.00000e+00  1.00000e+00]
 [ 3.77604e-04  1.30208e-03 -2.50000e+01 -1.00000e+01  1.00000e+00]]


In [10]:
import stanpy as stp

l = 5 #m
s = {"EI":32000, "GA":20000, "l":l, "q":2}
Fik = stp.tr_Q(**s)
print(Fik)

[[ 1.00000e+00  5.00000e+00 -3.90625e-04 -9.01042e-04  3.77604e-04]
 [ 0.00000e+00  1.00000e+00 -3.90625e-04 -9.01042e-04  1.30208e-03]
 [ 0.00000e+00  0.00000e+00  1.00000e+00  5.00000e+00 -2.50000e+01]
 [ 0.00000e+00  0.00000e+00 -0.00000e+00  1.00000e+00 -1.00000e+01]
 [ 0.00000e+00  0.00000e+00  0.00000e+00  0.00000e+00  1.00000e+00]]


In [11]:
import stanpy as stp

l = 5 #m
s = {"EI":32000, "GA":20000, "l":l, "q":2, "N":-1000}
load_integral_R = stp.calc_load_integral_R(x=[0,l/2,l],**s)
print(load_integral_R)

[[ 0.00000e+00  0.00000e+00  0.00000e+00 -0.00000e+00  1.00000e+00]
 [-2.17002e-04  1.69574e-04 -6.46700e+00 -5.00000e+00  1.00000e+00]
 [ 4.38933e-04  1.31535e-03 -2.45611e+01 -1.00000e+01  1.00000e+00]]


In [12]:
import stanpy as stp

l = 5 #m
s = {"EI":32000, "GA":20000, "l":l, "q":2, "N":-1000}
Fik = stp.tr_R(**s)
print(Fik)

[[ 1.00000e+00  4.57087e+00 -3.83767e-04 -4.29130e-04  4.38933e-04]
 [ 0.00000e+00  6.16233e-01 -1.35698e-04 -3.83767e-04  1.31535e-03]
 [ 0.00000e+00  4.57087e+03  6.16233e-01  4.57087e+00 -2.45611e+01]
 [ 0.00000e+00  0.00000e+00  0.00000e+00  1.00000e+00 -1.00000e+01]
 [ 0.00000e+00  0.00000e+00  0.00000e+00  0.00000e+00  1.00000e+00]]


In [13]:
import stanpy as stp

x = sym.Symbol("x")
E = 3*10**7  # kN/m2
b = 0.2  # m
hi = 0.3  # m
hk = 0.4  # m
l = 3  # m
hx = hi + (hk - hi) / l * x

cs_props = stp.cs(b=b, h=hx)
s = {"E": E, "cs": cs_props, "l": l, "q":10}
load_integral_Q = stp.calc_load_integral_Q_poly(x=[0,l/2,l],**s)

print(load_integral_Q)

[[ 0.00000e+00  0.00000e+00  0.00000e+00  0.00000e+00  1.00000e+00]
 [ 1.18053e-04  2.94153e-04 -1.12500e+01 -1.50000e+01  1.00000e+00]
 [ 1.47479e-03  1.73666e-03 -4.50000e+01 -3.00000e+01  1.00000e+00]]


In [14]:
import stanpy as stp

x = sym.Symbol("x")
E = 3*10**7  # kN/m2
b = 0.2  # m
hi = 0.3  # m
hk = 0.4  # m
l = 3  # m
hx = hi + (hk - hi) / l * x

cs_props = stp.cs(b=b, h=hx)
s = {"E": E, "cs": cs_props, "l": l, "q":10}

Fik = stp.tr_Q_poly(**s)
print(Fik)

[[ 1.00000e+00  3.00000e+00 -2.50000e-04 -2.15168e-04  1.47479e-03]
 [ 0.00000e+00  1.00000e+00 -1.45833e-04 -1.87500e-04  1.73666e-03]
 [ 0.00000e+00  0.00000e+00  1.00000e+00  3.00000e+00 -4.50000e+01]
 [ 0.00000e+00  0.00000e+00  0.00000e+00  1.00000e+00 -3.00000e+01]
 [ 0.00000e+00  0.00000e+00  0.00000e+00  0.00000e+00  1.00000e+00]]


In [15]:
import stanpy as stp

x = sym.Symbol("x")
E = 3*10**7  # kN/m2
b = 0.2  # m
hi = 0.3  # m
hk = 0.4  # m
l = 3  # m
hx = hi + (hk - hi) / l * x

cs_props = stp.cs(b=b, h=hx)
s = {"E": E, "cs": cs_props, "l": l, "q":10, "N":-1000}
load_integral_R = stp.calc_load_integral_R_poly(x=[0,l/2,l],**s)

print(load_integral_R)

[[ 0.00000e+00  0.00000e+00  0.00000e+00 -0.00000e+00  1.00000e+00]
 [ 1.17545e-04  2.92291e-04 -1.11325e+01 -1.50000e+01  1.00000e+00]
 [ 1.45456e-03  1.70226e-03 -4.35454e+01 -3.00000e+01  1.00000e+00]]


In [16]:
import stanpy as stp

x = sym.Symbol("x")
E = 3*10**7  # kN/m2
b = 0.2  # m
hi = 0.3  # m
hk = 0.4  # m
l = 3  # m
hx = hi + (hk - hi) / l * x

cs_props = stp.cs(b=b, h=hx)
s = {"E": E, "cs": cs_props, "l": l, "q":10, "N":-1000}

Fik = stp.tr_R_poly(**s)
print(Fik)

[[ 1.00000e+00  2.78942e+00 -2.40910e-04 -2.10583e-04  1.45456e-03]
 [ 0.00000e+00  8.18939e-01 -1.35638e-04 -1.81061e-04  1.70226e-03]
 [ 0.00000e+00  2.78942e+03  7.59090e-01  2.78942e+00 -4.35454e+01]
 [ 0.00000e+00  0.00000e+00  0.00000e+00  1.00000e+00 -3.00000e+01]
 [ 0.00000e+00  0.00000e+00  0.00000e+00  0.00000e+00  1.00000e+00]]
